# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb",
         "Deck": "01_deck.ipynb"}

modules = ["card.py",
           "deck.py"]

doc_url = "https://Rakeshsuku.github.io/sampleproj/"

git_url = "https://github.com/Rakeshsuku/sampleproj/tree/master/"

def custom_doc_links(name): return None
